language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev


script:
  - cmake -DCMAKE_CXX_FLAGS=-Werror .
  - make

after_success:
  - cd tests
  - python functional_tests.py ../src/fontbm

notifications:
  email: false
