language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6

before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
  - sudo apt-get install -qq libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev

script:
  - cmake -DCMAKE_CXX_FLAGS=-Werror .
  - make

after_success:
  - cd tests
  - python functional_tests.py ../src/fontbm

notifications:
  email: false
