os:
  - Visual Studio 2015

configuration: 
  - Debug
  - Release
  
platform:
  - x86

before_build:
  - git submodule init && git submodule update
  - cd c:\projects\fontbm
  - cmake -G "Visual Studio 14" -DBOOST_ROOT="C:\Libraries\boost" -DBOOST_LIBRARYDIR="C:\Libraries\boost\stage"
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  

build:
  project: fontbm.vcxproj
