os:
  - Visual Studio 2015

configuration: 
  - Debug
  - Release
  
platform:
  - x86

before_build:
  - ps: git submodule update --init --recursive
  - echo Running cmake...
  - cd c:\projects\fontbm
  - cmake -G "Visual Studio 14"
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  

build:
  project: fontbm.vcxproj
