os:
  - Visual Studio 2015

configuration: 
  - Debug
  - Release
  
platform:
  - x86
  
install:
  - mkdir C:\temp
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - 7z x SDL2-devel-2.0.3-VC.zip -oC:\temp\SDL2
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.0-VC.zip
  - 7z x SDL2_image-devel-2.0.0-VC.zip -oC:\temp\SDL2_image
  - appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.12-VC.zip
  - 7z x SDL2_ttf-devel-2.0.12-VC.zip -oC:\temp\SDL2_ttf
  - mkdir C:\Libraries\SDL2
  - cp C:\temp\SDL2\include\*.* C:\Libraries\SDL2
  - cp C:\temp\SDL2_image\include\*.* C:\Libraries\SDL2
  - cp C:\temp\SDL2_ttf\include\*.* C:\Libraries\SDL2

before_build:
  # current appveyour workers don't have boost libraries for vs2015, so we need build them
  - cd C:\Libraries\boost_1_58_0
  # boost 1.58 doesn't know about vs2015, so we need a little patch here
  - ps: (gc C:\Libraries\boost_1_58_0\boost\config\compiler\visualc.hpp).replace('_MSC_FULL_VER > 190022310', '_MSC_FULL_VER > 190023026') | sc C:\Libraries\boost_1_58_0\boost\config\compiler\visualc.hpp
  - .\bootstrap
  - .\b2 --with-system --with-filesystem --with-program_options --with-regex
  - cd C:\projects\fontbm
  - git submodule init && git submodule update  
  - cmake -G "Visual Studio 14 2015" -DBOOST_ROOT="C:\Libraries\boost_1_58_0" -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_MULTITHREADED=ON -DCMAKE_PREFIX_PATH="C:\Libraries"
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  

build:
  project: fontbm.vcxproj
