os:
  - Visual Studio 2015

configuration: 
  - Debug
  - Release
  
platform:
  - x86

before_build:
  - cd C:\Libraries\boost_1_58_0
  - .\bootstrap
  - .\b2 --with-system --with-filesystem
  - cd C:\projects\fontbm
  - git submodule init && git submodule update  
  - cmake -G "Visual Studio 14" -DBOOST_ROOT="C:\Libraries\boost"
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  

build:
  project: fontbm.vcxproj
